
package View;

import static Controller.TelaPrincipalController.acessarTelaAdministrador;
import static Controller.TelaPrincipalController.acessarTelaDocente;
import static Controller.TelaPrincipalController.acessarTelaEstudante;
import static Controller.TelaPrincipalController.acessarTelaTCC;
import static Controller.TelaPrincipalController.dataActual;
import static Controller.TelaPrincipalController.querSair;
import Model.*;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Gomes
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menucadastro = new javax.swing.JMenu();
        MenCadAdmin = new javax.swing.JMenuItem();
        MenCadDoc = new javax.swing.JMenuItem();
        MenCadEsd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenCadTcc = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MenRelAdmin = new javax.swing.JMenuItem();
        MenRelDoc = new javax.swing.JMenuItem();
        MenRelEst = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenRelTCC = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        MenVerCurCig = new javax.swing.JMenuItem();
        MenVerCurEst = new javax.swing.JMenuItem();
        MenVerCurInfo = new javax.swing.JMenuItem();
        MenVerCurMat = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenAjuSobre = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenOpcSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGA TCC - Tela Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(680, 480));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1009, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sigatcc.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Usuário:");

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_usuario.setText("Usuario");

        lbl_data.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_data.setText("Data");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbl_usuario)
                    .addComponent(jLabel5)
                    .addComponent(lbl_data))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_data)
                .addGap(23, 23, 23))
        );

        Menucadastro.setText("Cadastro");
        Menucadastro.setEnabled(false);

        MenCadAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MenCadAdmin.setText("Administrador");
        MenCadAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadAdminActionPerformed(evt);
            }
        });
        Menucadastro.add(MenCadAdmin);

        MenCadDoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        MenCadDoc.setText("Docente");
        MenCadDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadDocActionPerformed(evt);
            }
        });
        Menucadastro.add(MenCadDoc);

        MenCadEsd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        MenCadEsd.setText("Estudante");
        MenCadEsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadEsdActionPerformed(evt);
            }
        });
        Menucadastro.add(MenCadEsd);
        Menucadastro.add(jSeparator1);

        MenCadTcc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        MenCadTcc.setText("TCC");
        MenCadTcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadTccActionPerformed(evt);
            }
        });
        Menucadastro.add(MenCadTcc);

        jMenuBar1.add(Menucadastro);

        MenuRelatorio.setText("Relatorio");
        MenuRelatorio.setEnabled(false);

        MenRelAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenRelAdmin.setText("Administradores");
        MenRelAdmin.setEnabled(false);
        MenuRelatorio.add(MenRelAdmin);

        MenRelDoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        MenRelDoc.setText("Docentes");
        MenRelDoc.setEnabled(false);
        MenuRelatorio.add(MenRelDoc);

        MenRelEst.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenRelEst.setText("Estudantes");
        MenuRelatorio.add(MenRelEst);
        MenuRelatorio.add(jSeparator2);

        MenRelTCC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        MenRelTCC.setText("TCC");
        MenuRelatorio.add(MenRelTCC);

        jMenuBar1.add(MenuRelatorio);

        jMenu5.setText("Ver TCC");

        jMenu6.setText("Por Curso");

        MenVerCurCig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenVerCurCig.setText("CIG");
        jMenu6.add(MenVerCurCig);

        MenVerCurEst.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenVerCurEst.setText("Estatística");
        jMenu6.add(MenVerCurEst);

        MenVerCurInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenVerCurInfo.setText("Informática");
        jMenu6.add(MenVerCurInfo);

        MenVerCurMat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenVerCurMat.setText("Matemática");
        jMenu6.add(MenVerCurMat);

        jMenu5.add(jMenu6);

        jMenu7.setText("Por Ano");

        jMenuItem13.setText("2021");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenuItem14.setText("2020");
        jMenu7.add(jMenuItem14);

        jMenuItem15.setText("2019");
        jMenu7.add(jMenuItem15);

        jMenuItem16.setText("2018");
        jMenu7.add(jMenuItem16);

        jMenu5.add(jMenu7);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Ajuda");

        MenAjuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenAjuSobre.setText("Sobre");
        MenAjuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSobreActionPerformed(evt);
            }
        });
        jMenu3.add(MenAjuSobre);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Opções");

        MenOpcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenOpcSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair_16px.png"))); // NOI18N
        MenOpcSair.setText("Sair");
        MenOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcSairActionPerformed(evt);
            }
        });
        jMenu4.add(MenOpcSair);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1338, 724));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //chamando o metodo da data actual
        dataActual();
    }//GEN-LAST:event_formWindowActivated

    private void MenOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcSairActionPerformed
        //metodo que pergunta ao usuario se quer sair ou nao
        querSair(); 
    }//GEN-LAST:event_MenOpcSairActionPerformed

    private void MenCadAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadAdminActionPerformed
        //metodo para acessar a tela do administraor
        acessarTelaAdministrador();
    }//GEN-LAST:event_MenCadAdminActionPerformed

    private void MenCadDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadDocActionPerformed
        // metodo para acessar a tela docente
        acessarTelaDocente();
    }//GEN-LAST:event_MenCadDocActionPerformed

    private void MenAjuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjuSobreActionPerformed

    private void MenCadEsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadEsdActionPerformed
        // metodo para acessar a tela estudante
        acessarTelaEstudante();
    }//GEN-LAST:event_MenCadEsdActionPerformed

    private void MenCadTccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadTccActionPerformed
        // metodo para acessar a tela de TCC
        acessarTelaTCC();
    }//GEN-LAST:event_MenCadTccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenAjuSobre;
    private javax.swing.JMenuItem MenCadAdmin;
    private javax.swing.JMenuItem MenCadDoc;
    private javax.swing.JMenuItem MenCadEsd;
    private javax.swing.JMenuItem MenCadTcc;
    private javax.swing.JMenuItem MenOpcSair;
    public static javax.swing.JMenuItem MenRelAdmin;
    public static javax.swing.JMenuItem MenRelDoc;
    private javax.swing.JMenuItem MenRelEst;
    private javax.swing.JMenuItem MenRelTCC;
    private javax.swing.JMenuItem MenVerCurCig;
    private javax.swing.JMenuItem MenVerCurEst;
    private javax.swing.JMenuItem MenVerCurInfo;
    private javax.swing.JMenuItem MenVerCurMat;
    public static javax.swing.JMenu MenuRelatorio;
    public static javax.swing.JMenu Menucadastro;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public static javax.swing.JLabel lbl_data;
    public static javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
